name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 重要：自动生成 gradlew（如果项目缺失）
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: current

    - name: Validate Gradle Wrapper
      run: ./gradlew help --no-daemon  # 验证gradlew可用性

    - name: Build with Gradle
      run: ./gradlew dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          build/distributions/*
          build/libs/*
